### ISSUE TITLE
Dependency in _checkouts directory does not work

### ISSUE THREAD

**Issue by aboroska** [Supersonido/rebar_mix#13]
The following config crashes `rebar3` if the dependency is linked in `_checkouts`
because `name` is `undefined` in `AppInfo`.

```
{deps, [jason]}.

{plugins, [rebar_mix]}.
{provider_hooks, [
  {pre,  [{compile, {mix, find_elixir_libs}}]},
  {post, [{compile, {mix, consolidate_protocols}}]}
]}.
```

Using the latest `rebar3` master.
`rebar 3.12.0+build.4448.refe2ac3217 on Erlang/OTP 22 Erts 10.5`

**Comment by tsloughter** [comment]
Yea, it only works with hex dependencies and when put in `_checkouts` the dep becomes a "project app". It would have to be able to understand `mix.lock` to work in `_checkouts`.

This might be possible when I or someone gets around to merging this plugin with https://github.com/Supersonido/rebar3_elixir which calls elixir functions to work with mix.lock https://github.com/Supersonido/rebar3_elixir/blob/master/src/rebar3_elixir_utils.erl#L174

**Comment by Supersonido** [comment]
It's already consolidated!!

**Comment by grzuy** [comment]
Hi 👋 

Thanks for this plugin!

Using rebar 3.24.0 on Erlang/OTP 27 Erts 15.2.3

Trying to `rebar3 get-deps` with an elixir local dep in `_checkouts` but still getting the `undefined` issue as reported above.

This is part of my output.

```
===> Verifying dependencies...
===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: badarg
===> Stack trace to the error location:
[{erlang,binary_to_atom,
         [undefined,utf8],
         [{error_info,#{module => erl_erts_errors}}]},
 {rebar_app_info,apply_overrides,2,
                 [{file,"/home/runner/work/rebar3/rebar3/apps/rebar/src/rebar_app_info.erl"},
                  {line,688}]},
```
