### ISSUE TITLE
not downloading deps dependencies

### ISSUE THREAD

**Issue by seanmcevoy** [Supersonido/rebar_mix#19]
i have about 6 hours of elixir/mix experience, which may ultimately be the problem.
but after much digging it looks like either a documentation or code error.
i'm trying to include an elixir app in my erlang project for the first time.
following the docs i have this rebar.config file, have tried each of the 3 plugins options, 

```
%% -*- erlang -*-
{plugins, [
           {rebar_mix, ".*", {git, "https://github.com/Supersonido/rebar_mix", {branch, "master"}}}
%           {rebar_mix, ".*", {git, "https://github.com/starbelly/rebar_mix.git", {branch, "fixup-protocol-consolidation"}}}
%           rebar_mix
          ]}.

{provider_hooks, [
    {pre,  [{compile, {mix, find_elixir_libs}}]},
    {post, [{compile, {mix, consolidate_protocols}}]}
]}.

{deps,[{swarm, ".*", {git, "https://github.com/bitwalker/swarm", {tag, "master"}}}]}.
```

am running these versions:

```
iex -v
Erlang/OTP 21 [erts-10.3] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]
IEx 1.10.3 (compiled with Erlang/OTP 21)

mix -v
Erlang/OTP 21 [erts-10.3] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]
Mix 1.10.3 (compiled with Erlang/OTP 21)

erl
Erlang/OTP 21 [erts-10.3] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]
Eshell V10.3  (abort with ^G)

rebar3 -v
rebar 3.13.2 on Erlang/OTP 21 Erts 10.3
```

i can download this elixir dep separately and compile it with mix, but when i try to try to use rebar3 and this rebar_mix plugin it fails to download the swarm deps:

```
===> Fetching rebar_mix (from {git,"https://github.com/Supersonido/rebar_mix",
                     {branch,"master"}})
===> Compiling rebar_mix
===> Verifying dependencies...
===> Fetching swarm (from {git,"https://github.com/bitwalker/swarm",
                 {ref,"4aee63d83ad5ee6ee095b38b3ff93a4dbb7c3400"}})
===> Compiling swarm
Compiling 1 file (.erl)
Compiling 10 files (.ex)

== Compilation error in file lib/swarm/tracker/tracker.ex ==
** (CompileError) lib/swarm/tracker/tracker.ex:9: module GenStateMachine is not loaded and could not be found
    (elixir 1.10.3) expanding macro: Kernel.use/2
    lib/swarm/tracker/tracker.ex:9: Swarm.Tracker (module)
===> Failed to compile application swarm with mix
```

**Comment by tsloughter** [comment]
This plugin can't figure out transitive dependencies for git repo deps so you have to use only hex elixir apps.

Use swarm from hex instead of git and see if that works:

`{swarm, "3.4.0"}`

**Comment by seanmcevoy** [comment]
ok, so this isn't expected to work. is it in the rebar_mix roadmap to add it as a feature or is there some blocker that makes it impossible?
will learn what hex is and try that out. failing that i can list the swarm deps separately in my own rebar.config.
cheers.

**Comment by tsloughter** [comment]
It is on the "roadmap" of sorts. You should try https://github.com/Supersonido/rebar3_elixir

The goal is to merge the two projects into 1 but no one has had the time to actually do that work.

You should definitely pick up Hex for dependencies, it is great both for Erlang and Elixir.

**Comment by Supersonido** [comment]
It's already consolidated!!
