### ISSUE TITLE
Missing hook find_elixir_libs

### ISSUE THREAD

**Issue by orzen** [Supersonido/rebar_mix#7]
I noticed that I can't use the current instructions with rebar_mix from hex.pm since find_elixir_libs was introduced in a later release. Maybe it's time for a new release Hex.pm release? =)

**Comment by lpil** [comment]
I just ran into this. What's the fix?

**Comment by tsloughter** [comment]
I'll publish a release now.

**Comment by tsloughter** [comment]
Done, try now.

**Comment by orzen** [comment]
> I just ran into this. What's the fix?

Use the latest version of the hex (0.3.0).

**Comment by orzen** [comment]
Thank you for the nice support and have a good day!
